#!/usr/bin/env python
# Uses https://github.com/cdown/srt
# Just copy it to srt_tools (must install the main module)

"""Changes the subtitles to avoid overlap."""

from __future__ import division

import srt
import datetime
import srt_tools.utils
import logging

log = logging.getLogger(__name__)


def parse_args():
    def srt_timestamp_to_milliseconds(parser, arg):
        try:
            delta = srt.srt_timestamp_to_timedelta(arg)
        except ValueError:
            parser.error("not a valid SRT timestamp: %s" % arg)
        else:
            return timedelta_to_milliseconds(delta)

    examples = {
        "Avoid subs overlaping": ""
    }

    parser = srt_tools.utils.basic_parser(description=__doc__, examples=examples)
    return parser.parse_args()


def fix_overlap(subtitles):
    prev = None
    subs = []
    for subtitle in subtitles:
        if prev:
           prev.end = subtitle.start
           subs.append(prev)
        prev = subtitle
    subs.append(subtitle)
    return subs


def main():
    args = parse_args()
    logging.basicConfig(level=args.log_level)
    srt_tools.utils.set_basic_args(args)
    inp = list(args.input)
    corrected_subs = fix_overlap(inp)
    output = srt_tools.utils.compose_suggest_on_fail(corrected_subs, strict=args.strict)

    try:
        args.output.write(output)
    except (UnicodeEncodeError, TypeError):  # Python 2 fallback
        args.output.write(output.encode(args.encoding))


if __name__ == "__main__":  # pragma: no cover
    main()
